INSERT INTO PRODUCTS(ID,NAME,PRICE) VALUES(1,'Biscuit',15.00);
INSERT INTO PRODUCTS(ID,NAME,PRICE) VALUES(2,'Chocolate',25.00);

INSERT INTO REVIEWS(ID,DESCRIPTION,RATING,PRODUCT_FK) VALUES(1,'Excellent Product',3.5,1);
INSERT INTO REVIEWS(ID,DESCRIPTION,RATING,PRODUCT_FK) VALUES(2,'Kids Loving',5.0,1);